services:
  - type: web
    name: notebook-runner-api
    env: docker
    plan: free
    dockerCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    dockerfilePath: ./Dockerfile.api
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: S3_ENDPOINT_URL
        sync: false
      - key: S3_REGION
        value: us-east-1
      - key: S3_BUCKET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: API_KEY
        sync: false

  - type: worker
    name: notebook-runner-worker
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.worker
    dockerCommand: celery -A app.worker.celery_app worker --loglevel=INFO
    autoDeploy: true
    envVars:
      - key: ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: S3_ENDPOINT_URL
        sync: false
      - key: S3_REGION
        value: us-east-1
      - key: S3_BUCKET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: API_KEY
        sync: false
    
